### ISSUE TITLE
[Bug]: System.IO.DirectoryNotFoundException: Could not find a part of the path

### ISSUE THREAD

**Issue by semenar-0** [clemlesne/blue-agent#323]
### Problem

Occasionally, the build process cannot locate certain files on the file system.

### Impact

build failed

### Short logs

2024-12-09T09:43:16.0340260Z ##[debug]System.IO.DirectoryNotFoundException: Could not find a part of the path '/app-root/azp-work/_tasks/Bash_6c731c3c-3c68-459a-a5c9-bde6e6595b5b/3.246.1/task.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.GetTaskDefiniton(TaskStep task) in /mnt/vss/_work/1/s/src/Agent.Worker/TaskManager.cs:line 496
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.Load(TaskStep task) in /mnt/vss/_work/1/s/src/Agent.Worker/TaskManager.cs:line 140
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsyncInternal() in /mnt/vss/_work/1/s/src/Agent.Worker/TaskRunner.cs:line 105
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync() in /mnt/vss/_work/1/s/src/Agent.Worker/TaskRunner.cs:line 76
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken) in /mnt/vss/_work/1/s/src/Agent.Worker/StepsRunner.cs:line 264

### Version

jammy

**Comment by semenar-0** [comment]
found issue
